FROM alpine:3.9 as builder
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add make
RUN apk add crosstool-ng
RUN addgroup -S buildgroup
RUN adduser -S builduser -G buildgroup
USER builduser
RUN mkdir -p ~/crosstool-ng
WORKDIR ~/crosstool-ng
RUN DEFCONFIG=/usr/lib/crosstool-ng-1.23.0/samples/armv8-rpi3-linux-gnueabihf/crosstool.config ct-ng defconfig
RUN ct-ng build