#!/usr/bin/env python3

import os
import subprocess
import sys

print ("I was called with", len(sys.argv), "argument(s)")
print ("This is the list", str(sys.argv))
print("Hello world!")
os.chdir("/HaveBuild")
subprocess.run(["cmake", "../HaveFun", "-DCMAKE_TOOLCHAIN_FILE=../HaveFun/Toolchain-rpi3.cmake"])
subprocess.run(["make"])